/**
 * @file
 * This file implements a virtual CAN adapter class,
 * which allows to parse and replay logging files
 * generated by Vector's CANalyzer software.
 *
 * This third-party software aims at establishing
 * compatibility with Vector's CANalyzer software.
 * The author is not affiliated with Vector.
 * Vector did neither endorse nor support this project.
 */

#include <CANalyzer/LoggingFile.h>


CANalyzerLoggingFile::CANalyzerLoggingFile()
   :CANAdapter(),
    f(0)
{
    adapter_type = ADAPTER_LOGFILE;
}


CANalyzerLoggingFile::CANalyzerLoggingFile(char* filename)
   :CANalyzerLoggingFile()
{
    parseFile(filename);
}


CANalyzerLoggingFile::~CANalyzerLoggingFile() {}


bool CANalyzerLoggingFile::parseFile(char* filename)
{
    // TODO
    return false;
}


